# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuzzifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('parameter', models.CharField(max_length=30)),
                ('deratajat', models.CharField(max_length=30)),
                ('hasil', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('datas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fuzzifikasi_Datas', to='Fuzzy.Datas')),
            ],
        ),
    ]
