# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0002_fuzzifikasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuzzifikasi',
            old_name='deratajat',
            new_name='deratjat',
        ),
        migrations.AlterField(
            model_name='fuzzifikasi',
            name='hasil',
            field=models.FloatField(default=0),
        ),
    ]
