# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0004_auto_20180720_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('permintaan', models.FloatField(default=0)),
                ('persediaan', models.FloatField(default=0)),
                ('produksi', models.FloatField(default=0)),
                ('a_predikat', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('az_predikat', models.FloatField(default=0)),
                ('datas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RuleBase_Datas', to='Fuzzy.Datas')),
            ],
        ),
    ]
