# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0005_rulebase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulebase',
            name='produksi',
        ),
    ]
