# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0006_remove_rulebase_produksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defuzzifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('hasil', models.FloatField(default=0)),
                ('datas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Defuzzifikasi_Datas', to='Fuzzy.Datas')),
            ],
        ),
    ]
