# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0007_defuzzifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('bulan', models.CharField(max_length=30)),
                ('minggu', models.CharField(max_length=30)),
                ('permintaan', models.IntegerField()),
                ('persediaan', models.IntegerField()),
                ('produksi', models.IntegerField()),
                ('datas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FileDatas_Datas', to='Fuzzy.Datas')),
            ],
        ),
    ]
