# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0008_filedatas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=30)),
                ('derajat', models.CharField(max_length=30)),
                ('hasil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='batas',
            name='datas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Filename_Batas', to='Fuzzy.FileName'),
        ),
    ]
