# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fuzzy', '0009_auto_20180722_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batas',
            name='datas',
        ),
        migrations.DeleteModel(
            name='Batas',
        ),
        migrations.DeleteModel(
            name='FileName',
        ),
    ]
